# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: 'en-US'
reviews:
  poem: false
  collapse_walkthrough: true
  auto_review:
    drafts: false
    labels:
      - 'dependencies'
    ignore_title_keywords:
      - 'WIP'
      - 'Draft'
      - 'DO NOT MERGE'
      - 'Work in Progress'
